# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('estimated_price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asados.Asado')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='invitation',
            name='invite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asados.User'),
        ),
        migrations.AddField(
            model_name='asado',
            name='attendee',
            field=models.ManyToManyField(related_name='Invitado', through='asados.Invitation', to='asados.User'),
        ),
        migrations.AddField(
            model_name='asado',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Organizador', to='asados.User'),
        ),
    ]
