# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asados', '0002_auto_20171022_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='asado',
            name='place',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='asado',
            name='attendee',
            field=models.ManyToManyField(related_name='Invitados', through='asados.Invitation', to='asados.User'),
        ),
    ]
