# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asados', '0003_auto_20171022_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asado',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
