# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asados', '0004_auto_20171023_1303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asado',
            options={'ordering': ['datetime']},
        ),
        migrations.RenameField(
            model_name='asado',
            old_name='date',
            new_name='datetime',
        ),
    ]
