# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 02:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asados', '0005_auto_20171023_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asado',
            old_name='estimated_price',
            new_name='estimated_cost',
        ),
    ]
