# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 05:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asados', '0006_auto_20171024_0214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=128)),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=7)),
                ('asado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='asados.Asado')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(default='', max_length=256)),
                ('designated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asados.User')),
                ('item_to_buy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asados.Item')),
            ],
        ),
    ]
