# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 06:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asados', '0007_item_purchaseorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='designated_user',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='item_to_buy',
        ),
        migrations.AddField(
            model_name='item',
            name='comment',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='item',
            name='designated_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asados.User'),
        ),
        migrations.DeleteModel(
            name='PurchaseOrder',
        ),
    ]
