# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asados', '0008_auto_20171024_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
