# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 05:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('asados', '0010_item_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(default='', max_length=256)),
                ('fullfilled', models.BooleanField(default=False)),
                ('required_quantity', models.IntegerField(default=0)),
                ('asado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='asados.Asado')),
            ],
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('drink', 'Drink'), ('food', 'Food')], max_length=64)),
                ('description', models.CharField(max_length=128, unique=True)),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='asado',
        ),
        migrations.RemoveField(
            model_name='item',
            name='designated_user',
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=128, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(re.compile('^[-\\w]+\\Z', 32), "Enter a valid 'slug' consisting of Unicode letters, numbers, underscores, or hyphens.", 'invalid')]),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='assignment',
            name='designated_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asados.User'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='required_supply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asados.Supply'),
        ),
        migrations.CreateModel(
            name='DrinkSupply',
            fields=[
            ],
            options={
                'indexes': [],
                'proxy': True,
            },
            bases=('asados.supply',),
        ),
        migrations.CreateModel(
            name='FoodSupply',
            fields=[
            ],
            options={
                'indexes': [],
                'proxy': True,
            },
            bases=('asados.supply',),
        ),
    ]
