# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 04:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asados', '0012_auto_20171026_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asado',
            name='estimated_cost',
        ),
    ]
